/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export type UserRole = "gestor_principal" | "gerente_loja" | "operador_vendas" | "admin" | "vendedor";

export interface User {
  id: string;
  name: string;
  email: string;
  username?: string;
  password?: string;
  role: UserRole;
  active: boolean;
  storeId?: string; // Assigned store branch id
}

export interface Category {
  id: string;
  name: string;
  description?: string;
  syncPending?: boolean;
}

export interface Product {
  id: string;
  code: string;
  name: string;
  category: string;
  purchasePrice: number; // For dynamic margin or profit tracking
  sellPrice: number;
  stock: number;
  minStock: number;
  unit: string; // e.g. "Unidade", "Kg", "Caixa"
  description?: string;
  storeId: string; // Isolated store
  syncPending?: boolean;
  type?: "produto" | "servico";
}

export interface StockMovement {
  id: string;
  productId: string;
  productName: string;
  type: "entrada" | "saida"; // "entrada" (restock), "saida" (sale or correction)
  quantity: number;
  reason: string; // e.g., "Venda", "Abastecimento", "Ajuste de inventário"
  date: string;
  user: string;
  storeId: string;
  syncPending?: boolean;
}

export interface DebtPayment {
  id: string;
  amount: number;
  date: string;
  method: string;
}

export interface Debt {
  id: string;
  customerId: string;
  customerName: string;
  description: string;
  initialAmount: number;
  currentAmount: number;
  date: string;
  status: "pendente" | "pago";
  payments: DebtPayment[];
  storeId: string;
  syncPending?: boolean;
}

export interface Customer {
  id: string;
  name: string;
  phone: string;
  email?: string;
  nif?: string;
  totalPurchases: number;
  notes?: string;
  storeId: string;
  syncPending?: boolean;
}

export interface SaleItem {
  productId: string;
  productName: string;
  quantity: number;
  price: number;
  costPrice: number; // Cached at sale time to compute accurate profit
  discount: number; // Discount per item
}

export type DocumentType = "FR" | "FP" | "OR" | "FT" | "FG";

export interface Sale {
  id: string;
  invoiceNumber: string; // e.g., FR-2026/01
  documentType: DocumentType; // FR=Factura Recibo, FP=Pro-forma, OR=Orçamento, FT=Factura (Cobrança), FG=Factura Global
  date: string;
  items: SaleItem[];
  subtotal: number;
  discount: number; // Global discount amount
  tax: number; // Calculated VAT (e.g. 14% or simplified)
  total: number;
  profit: number;
  paymentMethod: "dinheiro" | "transferencia" | "multicaixa" | "misto" | "mcx_express";
  receivedAmount: number;
  changeAmount: number;
  clientId?: string;
  clientName: string;
  clientNif?: string;
  cashierId: string;
  cashierName: string;
  status: "ativa" | "cancelada";
  cancelReason?: string;
  hash: string; // AGT Electronic signature SHA-1 fragment
  agtCertCode: string; // App certified by AGT code e.g. "415/AGT/2026"
  mcxPhone?: string; // Multicaixa Express phone number
  mcxRef?: string; // EMIS payment reference code
  storeId: string; // Multi-store isolation id
  syncPending?: boolean;
}

export type TransactionType = "entrada" | "saida";

export interface FinancialTransaction {
  id: string;
  type: TransactionType;
  category: string; // e.g. "Venda", "Abastecimento", "Salários", "Renda", "Ajuste"
  amount: number;
  description: string;
  date: string;
  referenceId?: string; // Links to Sale ID if generated by sales
  storeId: string;
  syncPending?: boolean;
}

export interface StoreBranch {
  id: string;
  name: string;
  code: string;
  location: string;
  tel: string;
}

export interface AppSettings {
  companyName: string;
  companyNif: string;
  companyPhone: string;
  companyEmail: string;
  companyAddress: string;
  companyIban?: string;
  taxRate: number; // Default 14% in Angola
  regime: string; // e.g. "Regime de Simplificação" or "Isento"
  printFormat: "a4" | "thermal";
  themeMode: "light" | "dark";
  companyLogoId: string; // "preset-modern" | "preset-palma" | "preset-shield" | "preset-basket" | "custom"
  customLogoUrl?: string; // Custom uploaded file logo dataURI
  licenseKey: string;
  licenseStatus: "active" | "expired";
  licenseExpiry: string; // ISO date string
  licenseType: "mensal" | "trimestral" | "semestral" | "anual" | "teste";
  networkMode?: "standalone" | "server" | "node";
  networkIp?: string;
  networkPort?: string;
  printerType?: "system" | "escpos";
  printerConnection?: "usb" | "network" | "bluetooth" | "serial";
  printerIp?: string;
  printerPort?: string;
  printerPaperWidth?: "58" | "80" | "a4";
}

export interface SaasTenant {
  id: string;
  name: string;
  nif: string;
  email: string;
  phone: string;
  address: string;
  planType: "starter" | "profissional" | "enterprise";
  status: "active" | "expired" | "pending" | "blocked";
  expiryDate: string;
  monthlyFee: number;
  productsLimit: number;
  invoicesLimit: number;
  deletedAt?: string;
}

export interface StockRequest {
  id: string;
  sourceStoreId: string;
  destinationStoreId: string;
  productId: string;
  productName: string;
  productCode: string;
  quantity: number;
  requestedBy: string;
  requestedAt: string;
  status: "pendente" | "aprovada" | "rejeitada";
  approvedBy?: string;
  approvedAt?: string;
}

export interface EmployeeDebt {
  id: string;
  userId: string; // The employee in debt
  userName: string; // The employee name
  amount: number;
  remainingAmount: number; // Remaining amount to be paid
  reason: "falta_relatorio" | "adiantamento_salario" | "produto_fiado" | "outro";
  description: string;
  date: string;
  status: "pendente" | "pago";
  payments: {
    id: string;
    amount: number;
    date: string;
    method: string;
    receivedBy: string; // Name of person who received the payment
  }[];
  storeId: string; // Multi-store isolation id
  registeredByUserId: string; // User ID who registered this debt
  registeredByName: string; // Name of user who registered this debt
  syncPending?: boolean;
}



